version: "3.8"

services:
  db:
    image: postgres
    container_name: credit_card_api_db
    ports:
      - "5433:5432"
    volumes:
      - ./initiate_sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credit_card_api_app
    expose:
      - 8000
    restart: always
    environment:
      - POSTGRES_DB_NAME=creditcard
      - POSTGRES_DB_USERNAME=creditcard
      - POSTGRES_DB_PASS=creditcard
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_PORT=5432
      - PORT=${PORT}
    command: >
            bash -c "npm start"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
